apiVersion: apps/v1

kind: Deployment


metadata:

  name: frontend-deployment

  namespace: portfolio-app


spec:

  replicas: 2


  selector:

    matchLabels:

      app: frontend


  template:

    metadata:

      labels:

        app: frontend


    spec:

      containers:

      - name: frontend

        image: vishnukantheti/k8s-frontend:v3


        ports:

        - containerPort: 80
