apiVersion: apps/v1

kind: Deployment


metadata:

  name: frontend-deployment

  namespace: portfolio-app


spec:

  replicas: {{ .Values.frontend.replicaCount }}


  selector:

    matchLabels:

      app: frontend


  template:

    metadata:

      labels:

        app: frontend


    spec:

      containers:

      - name: frontend

        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}" 


        ports:

        - containerPort: 80
