apiVersion: apps/v1

kind: Deployment


metadata:

  name: mysql-deployment

  namespace: portfolio-app


spec:

  replicas: 1


  selector:

    matchLabels:

      app: mysql


  template:

    metadata:

      labels:

        app: mysql


    spec:

      containers:

      - name: mysql

        image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"


        ports:

        - containerPort: {{ .Values.mysql.port }}


        env:

        - name: MYSQL_ROOT_PASSWORD

          valueFrom:

            secretKeyRef:

              name: mysql-secret

              key: MYSQL_ROOT_PASSWORD


        volumeMounts:

        - name: mysql-storage

          mountPath: /var/lib/mysql


      volumes:

      - name: mysql-storage

        persistentVolumeClaim:

          claimName: mysql-pvc
