apiVersion: v1

kind: Service


metadata:

  name: mysql-service

  namespace: portfolio-app


spec:

  selector:

    app: mysql


  ports:

  - port: {{ .Values.mysql.port }}

    targetPort: 3306


  type: ClusterIP
